---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu-14.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
      customize:
        memory: 1536
        natdnshostresolver1: "on"
      network:
        - ["forwarded_port", {guest: 80, host: 8000}]

suites:
  - name: default
    run_list:
      - recipe[packagist::default]